package com.june.project.community.model;

public class LikedInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likedinfo.id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likedinfo.comment_id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likedinfo.user_id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likedinfo.status
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likedinfo.id
     *
     * @return the value of likedinfo.id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likedinfo.id
     *
     * @param id the value for likedinfo.id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likedinfo.comment_id
     *
     * @return the value of likedinfo.comment_id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likedinfo.comment_id
     *
     * @param commentId the value for likedinfo.comment_id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likedinfo.user_id
     *
     * @return the value of likedinfo.user_id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likedinfo.user_id
     *
     * @param userId the value for likedinfo.user_id
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likedinfo.status
     *
     * @return the value of likedinfo.status
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likedinfo.status
     *
     * @param status the value for likedinfo.status
     *
     * @mbg.generated Thu Aug 06 16:22:14 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}